Lesson 18
supronva-github/test-guru pull request #17
Opened 2023-06-28 01:08 UTC by supronva-github

2023-06-28 06:52 UTC, BubuntuClu requested changes

2023-06-28 06:52 UTC, BubuntuClu commented on app/services/AchievementService.rb
> +        reward(badge) if level_complete?(badge.rule.options.to_i)
это может вылиться в огромный кейс. при добавлении нового имени правила, тебе надо будет тут дописывать новую ветку. как можно этого избежать?

2023-06-28 06:52 UTC, BubuntuClu commented on app/services/AchievementService.rb
> +    @test_passage.successfully?
это не отвечает на вопрос пройдена ли полностью категоиря или уровень. в категории может быть больше одного теста. и по уровню тоже самое

2023-06-28 06:52 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      AchievementService.new(@test_passage).call
у тебя в каждом методе есть проверка на успешное прохождение. если оно не успшное то все проверки дадут false. стоит ли тогда вызывать сервис и тратить ресурсы сервера на код, который ничего не сделает?

2023-07-03 01:53 UTC, supronva-github commented on app/services/AchievementService.rb
> +    @test_passage.successfully?
поправил

2023-07-03 01:53 UTC, supronva-github commented on app/controllers/test_passages_controller.rb
> +      AchievementService.new(@test_passage).call
поправил

2023-07-03 01:54 UTC, supronva-github commented on app/services/AchievementService.rb
> +        reward(badge) if level_complete?(badge.rule.options.to_i)
сделал через send

2023-07-03 07:49 UTC, BubuntuClu requested changes

2023-07-03 07:49 UTC, BubuntuClu commented on app/services/AchievementService.rb
> +    user_finished_all_tests_by_category = all_ready_tests_by_category.all? do |test|
сколько запросов к БД у тебя тут получается? выглдит как очень сильно неоптимизированный код.

почему бы просто не сравнить два результата запросов к БД?

2023-07-03 07:49 UTC, BubuntuClu commented on app/services/AchievementService.rb
> +    user_finished_all_tests_by_level = all_ready_tests_by_level.all? do |test|
тут тоже самое

2023-07-03 07:49 UTC, BubuntuClu commented on app/services/AchievementService.rb
> +    @user.test_passages.where(test_id: @test.id).count == 1
не учитывается что тест пройден успешно

2023-07-03 07:49 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      AchievementService.new(@test_passage).call
не вижу чтобы поправил

2023-07-03 10:09 UTC, supronva-github commented on app/services/AchievementService.rb
> +    @user.test_passages.where(test_id: @test.id).count == 1
исправил

2023-07-03 10:10 UTC, supronva-github commented on app/services/AchievementService.rb
> +    user_finished_all_tests_by_level = all_ready_tests_by_level.all? do |test|
сделал через сравнение 2х запросов

2023-07-03 10:10 UTC, supronva-github commented on app/services/AchievementService.rb
> +    user_finished_all_tests_by_category = all_ready_tests_by_category.all? do |test|
сделал через сравнение 2х запросов

2023-07-04 08:35 UTC, BubuntuClu commented on app/services/AchievementService.rb
> +    @user.test_passages.where(test_id: @test.id, finished: true).count == 1
это неправильная проверка. ты отфильтровываешь неудачные попытки. если ты добавил проверку что вызываешь сервис только для успешных, то тут уже не надо дополнительно фильтровать

2023-07-04 15:22 UTC, merged