Lesson 9
supronva-github/test-guru pull request #8
Opened 2022-12-22 16:59 UTC by supronva-github

2022-12-23 06:36 UTC, BubuntuClu requested changes

2022-12-23 06:36 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound do |e|
с таким подходом, если упадет ошибка, ты поймешь в каком контроллере она упала? как выглядит текст ошибки?

2022-12-23 06:36 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[start]
для одного экшена не стоит делать колбэк. усложняешь логику и больше кода из-за этого пишешь

2022-12-23 06:36 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    if test_passage.success?
если логика метода `success?` будет тяжелой, то ты дважды проверяешь одно и тоже с тяжелым алгоритмом, . попробуй объединить в один метод

хэлпер может отдавать сразу HTML разметку

2022-12-23 06:36 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +<% if @test_passage.current_question != nil %>
у тебя есть метод `completed?` для этой проверки, используй лучше его

2022-12-23 16:57 UTC, supronva-github commented on app/controllers/application_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound do |e|
Текст ошибки: `Couldn't find Test with 'id'=22`
Думаю да - пойму

2022-12-23 16:58 UTC, supronva-github commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[start]
поправил
Для поиска user я оставил  callback

2022-12-23 16:58 UTC, supronva-github commented on app/helpers/test_passages_helper.rb
> +    if test_passage.success?
Переделал в 1 метод

2022-12-23 16:58 UTC, supronva-github commented on app/views/test_passages/show.html.erb
> +<% if @test_passage.current_question != nil %>
Done

2022-12-24 07:34 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound do |e|
а из какого контроллера? ты ищешь тест в контроллере тестов и в контроллере вопросов

2022-12-24 07:36 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[start]
почему так?

2022-12-27 15:45 UTC, supronva-github commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[start]
решил что так более наглядно и понятно)

2022-12-27 15:46 UTC, merged